server:
  port: 8080
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 100MB  # Max file size.
      max-request-size: 100MB # Max request size.
  application:
    name: tran-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL8的驱动程序类
    url: jdbc:mysql://47.93.131.24:3306/w_tran1?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: 123456 # 数据库连接密码

# 监控中心
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health
  endpoint:
    health:
      show-details: always

# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.chc.pojo.entity

# tkMybatis配置
mapper:
  mappers: com.chc.base.BaseMapper
  # 设置true以后，会去判断 insert 和 update 中符串类型!=''
  not-empty: false
  identity: MYSQL